# Try to find the READLINE librairies
#  READLINE_FOUND - system has READLINE lib
#  READLINE_INCLUDE_DIR - the READLINE include directory
#  READLINE_LIBRARIES - Libraries needed to use READLINE


if (READLINE_INCLUDE_DIR AND READLINE_LIBRARIES)
  # Already in cache, be silent
  set(READLINE_FIND_QUIETLY TRUE)
endif (READLINE_INCLUDE_DIR AND READLINE_LIBRARIES)

find_package (Curses)

if (CURSES_FOUND)
  find_path(READLINE_INCLUDE_DIR NAMES history.h readline/history.h)
  find_library(READLINE_LIBRARIES NAMES readline)

  if (READLINE_INCLUDE_DIR)
    SET(${UPPER_NAME}_HAVE_READLINE "1" CACHE TYPE DOCSTRING)
    SET(${UPPER_NAME}_HAVE_READLINE_HISTORY_H ON CACHE TYPE BOOL)
    SET(${UPPER_NAME}_HAVE_READLINE_READLINE_H ON CACHE TYPE BOOL)
  endif (READLINE_INCLUDE_DIR)

  set(READLINE_INCLUDE_DIR ${READLINE_INCLUDE_DIR} ${CURSES_INCLUDE_DIR})
  set(READLINE_LIBRARIES ${READLINE_LIBRARIES} ${CURSES_LIBRARIES})
endif (CURSES_FOUND)


include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(READLINE DEFAULT_MSG READLINE_INCLUDE_DIR READLINE_LIBRARIES)

mark_as_advanced(READLINE_INCLUDE_DIR READLINE_LIBRARIES)

if (READLINE_INCLUDE_DIR MATCHES NOTFOUND OR READLINE_LIBRARIES MATCHES NOTFOUND)
  set(READLINE_FOUND FALSE)
else (READLINE_INCLUDE_DIR MATCHES NOTFOUND OR READLINE_LIBRARIES MATCHES NOTFOUND)
  set(READLINE_FOUND TRUE)
endif (READLINE_INCLUDE_DIR MATCHES NOTFOUND OR READLINE_LIBRARIES MATCHES NOTFOUND)
